//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovaya_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlannedExpenses
    {
        public int Id { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public int ExpenseTypesId { get; set; }
        public int BudgetId { get; set; }
    
        public virtual Budget Budget { get; set; }
        public virtual ExpenseTypes ExpenseTypes { get; set; }
    }
}
